server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: authschema
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=authschema
    username: myuser
    password: 123

  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml

security:
  oauth2:
    resource:
      id: oauth2_application
      filter-order: 3
  enabled: false

logging:
  level:
    org.springframework.security: DEBUG


